StripeShop/StripeShop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/', include('shopapp.urls')),
]

StripeShop/shopapp/urls.py
from django.urls import path
from . import views

app_name = 'shopapp'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('item/<int:pk>/', views.item_detail_view, name='item_details'),
    path('buy/<int:pk>/', views.buy_item, name='buy_item'),
    path('success/', views.success_view, name='success'),
    path('cancel/', views.cancel_view, name='cancel'),
]

StripeShop/shopapp/models.py
from django.db import models


class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

StripeShop/shopapp/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import Item
import stripe
from django.conf import settings

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.
def index_view(request):
    items = Item.objects.all()
    return render(request, 'index.html', {'items': items})

def item_detail_view(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'item.html', {'item': item, 'STRIPE_PUBLIC_KEY': settings.STRIPE_PUBLIC_KEY})

def buy_item(request, pk):
    item = get_object_or_404(Item, pk=pk)

    session = stripe.checkout.Session.create(
    line_items= [{
      'price_data': {
        'currency': 'rub',
        'product_data': {
          'name' : item.name,
        },
        'unit_amount': int(item.price * 100)
      },
      'quantity': 1,
    }],
    mode= 'payment',
    success_url="http://127.0.0.1:8000/shopapp/success",
    cancel_url="http://127.0.0.1:8000/shopapp/cancel",
    )
    return JsonResponse({
        'session_id': session.id,
        'public_key': settings.STRIPE_PUBLIC_KEY
    })

def success_view(request):
    return render(request, 'success.html')

def cancel_view(request):
    return render(request, 'cancel.html')

StripeShop/shopapp/templates/cancel.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Оплата отменена</title>
</head>
<body>
    <h1>Оплата не прошла</h1>
    <a href="{% url 'shopapp:index' %}">Вернуться в магазин</a>
</body>
</html>

StripeShop/shopapp/templates/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StripeShop</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <header>
        <h1>StripeShop</h1>
    </header>
    <main>
        <div class="products">
            {% for item in items %}
            <div class="product">
                <h2><a href="{% url 'shopapp:item_details' item.id %}">{{ item.name }}</a></h2>
                <p>{{ item.price }} руб.</p>
            </div>
            {% endfor %}
        </div>
    </main>
    <footer>
        <p>2025 StripeShop</p>
    </footer>
</body>
</html>

StripeShop/shopapp/templates/item.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Информация о товаре {{ item.name }}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'item.css' %}">
    <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
    <div class="product-container">
        <h1 class="product-name">{{ item.name }}</h1>
        <p class="product-description">{{ item.description }}</p>
        <p class="product-price">Цена: {{ item.price }} руб.</p>
        <form>
            {% csrf_token %}
            <button id="buy-button">Купить</button>
        </form>
    </div>
    <script>
        document.getElementById("buy-button").addEventListener("click", async function (event) {
            event.preventDefault();
            const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
            const response = await fetch("/shopapp/buy/{{ item.id }}/", {
                method: "POST",
                headers: { "Content-Type": "application/json", "X-CSRFToken": csrftoken },
                body: JSON.stringify({})
            });
            const data = await response.json();
            Stripe("{{ STRIPE_PUBLIC_KEY }}").redirectToCheckout({ sessionId: data.session_id });
        });
    </script>
</body>
</html>

StripeShop/shopapp/templates/success.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Успешная оплата</title>
</head>
<body>
    <h1>Спасибо за покупку!</h1>
    <a href="{% url 'shopapp:index' %}">Вернуться в магазин</a>
</body>
</html>